
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
secrets: # bind secret to account
  - name: cd-secret
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin-role-binding
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: homework
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

