apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: homework
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 8080
    targetPort: nginx-port #link to pod named port
  - name: metrics-service-port
    port: 9090
    targetPort: 9090