apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{.Values.namespace.name}}
data:
  nginx.conf: |
      server {
          listen {{.Values.containers.nginx.port.value}};
          server_name localhost;
          location / {
            root /homework;
            autoindex on;
          }
      }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  namespace: {{.Values.namespace.name}}
  labels:
    app: nginx
spec:
  replicas: {{.Values.containers.nginx.replicas}}
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: homework
                  operator: In
                  values:
                  - "true"
      initContainers:
      - name: init
        image: busybox
        command:
          - /bin/sh
          - -c
          - echo '<html><body><h1>INIT</h1></body></html>' > /init/index.html
        volumeMounts:
        - name: shared
          mountPath: /init
      containers:
      - name: {{.Values.containers.nginx.name}}
        image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{.Values.containers.nginx.port.value}}
          name: {{.Values.containers.nginx.port.name}}
        volumeMounts:
        - name: shared
          mountPath: /homework
        - name: conf
          mountPath: /etc/nginx/conf.d
{{ if .Values.probes.enabled }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /index.html
            port: {{.Values.containers.nginx.port.value}}
          initialDelaySeconds: 10
          periodSeconds: 2
{{ end }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: shared
        emptyDir: {}
      - name: conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf