apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{.Values.namespace.name}}
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: {{.Values.service.port.value}}
    # name to create link to this port Number from ingress
    name: {{.Values.service.port.name}}
    #link to pod named port
    targetPort: {{.Values.containers.nginx.port.name}} 